name: Test Anaconda Installer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-bash:
    name: Test Anaconda Installer with Bash
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Make Script Executable
        run: chmod +x install_anaconda.sh

      - name: Run Installer with Bash
        run: ./install_anaconda.sh
        shell: bash

  test-zsh:
    name: Test Anaconda Installer with Zsh
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Zsh
        run: brew install zsh

      - name: Make Script Executable
        run: chmod +x install_anaconda.sh

      - name: Run Installer with Zsh
        run: zsh ./install_anaconda.sh
