name: Test Anaconda Installer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-bash:
    name: Test Anaconda Installer with Bash
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Make Script Executable
        run: chmod +x install_anaconda.sh

      - name: Run Installer with Bash
        shell: bash
        run: ./install_anaconda.sh

      - name: Test Conda with Bash
        run: |
          export PATH="$HOME/anaconda3/bin:$PATH"
          conda --version

  test-zsh:
    name: Test Anaconda Installer with Zsh
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Zsh
        run: brew install zsh

      - name: Make Script Executable
        run: chmod +x install_anaconda.sh

      - name: Run Installer with Zsh
        shell: zsh
        run: ./install_anaconda.sh

      - name: Test Conda with Zsh
        run: |
          export PATH="$HOME/anaconda3/bin:$PATH"
          conda --version
