name: Test Setup Script

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y zsh curl git

    - name: Run setup script
      run: |
        chmod +x setup_env.sh
        ./setup_env.sh

    - name: Verify the installation
      run: |
        git --version
        zsh --version
        fzf --version || echo "fzf not found"
        if [ -d "$HOME/.oh-my-zsh" ]; then echo "Oh My Zsh installed"; else echo "Oh My Zsh not installed"; fi
        if [ -d "$HOME/.zsh/zsh-syntax-highlighting" ]; then echo "zsh-syntax-highlighting installed"; else echo "zsh-syntax-highlighting not installed"; fi
        if [ -d "$HOME/.zsh/zsh-autosuggestions" ]; then echo "zsh-autosuggestions installed"; else echo "zsh-autosuggestions not installed"; fi
        if [ -f "$HOME/.zshhrc/workspace/cloud-setup/.zshrc" ]; then echo ".zshrc file is present"; else echo ".zshrc file not found"; fi
