name: Test Setup Script

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Ensure curl is installed
      run: sudo apt-get update && sudo apt-get install -y curl

    - name: Uninstall existing dependencies if present
      run: |
        if command -v zsh >/dev/null 2>&1; then
          echo "Uninstalling zsh..."
          sudo apt-get remove -y zsh
        fi
        if command -v java >/dev/null 2>&1; then
          echo "Uninstalling Java..."
          sudo apt-get remove -y openjdk-11-jdk
        fi
        if command -v zellij >/dev/null 2>&1; then
          echo "Uninstalling zellij..."
          cargo uninstall zellij
        fi

    - name: Run setup script with auto-confirmation for zellij installation
      run: |
        chmod +x setup_env.sh
        echo "y" | ./setup_env.sh

    - name: Verify the initial installation
      run: |
        git --version
        zsh --version
        java -version || echo "Java not found"
        zellij --version || echo "zellij not found"
        if [ -d "$HOME/.oh-my-zsh" ]; then echo "Oh My Zsh installed"; else echo "Oh My Zsh not installed"; fi
        if [ -d "$HOME/.zsh/zsh-syntax-highlighting" ]; then echo "zsh-syntax-highlighting installed"; else echo "zsh-syntax-highlighting not installed"; fi
        if [ -d "$HOME/.zsh/zsh-autosuggestions" ]; then echo "zsh-autosuggestions installed"; else echo "zsh-autosuggestions not installed"; fi
